server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sameera12345/microservices-course-cloud-config
          search-paths:
            - 'service-config/*service'